version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.0.1
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - 8080:8080
    command: start-dev
    networks:
      - customer-network
  localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:4510-4559:4510-4559"
      - "127.0.0.1:4566:4566"
    environment:
      - TMPDIR=/private/var/folders/v7/_qxvr2d54m565vdm9r8yv_140000gq/T/
      - SERVICES=sqs
      - DEBUG=${DEBUG-}
      - DATA_DIR=/Users/colaborador/localstack/data
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
      - EXTRA_CORS_ALLOWED_ORIGINS=app://.
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - customer-network

networks:
  customer-network:
    driver: bridge
