server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    spring.jpa.defer-datasource-initialization: true

  jackson:
    default-property-inclusion: non_null

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/CustomerServiceRealm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: login-app
      principal-attribute: preferred_username

aws:
  access-key: 123
  secret-key: 123
  region: us-east-1
  endpoint: http://localhost:4566
  customer-queue: http://localhost:4566/000000000000/customer-service-queue